version: '3.9'

services:
  mcp:
    image: studious_mcp:latest
    ports:
      - "3030:3030"
    environment:
      RUST_LOG: debug
      DATABASE_URL: sqlite:///app/db/db.sqlite
    volumes:
      - ./crates/app/db:/app/db
    restart: unless-stopped
